#!/bin/sh -eux

systemctl --user stop container-apt-cacher-ng.service || true
podman container rm -f apt-cacher-ng || true

podman build -t apt-cacher-ng -f - <<EOF

FROM    debian:testing

RUN     apt-get update && \
        echo 'apt-cacher-ng apt-cacher-ng/bindaddress select localhost' | debconf-set-selections && \
        DEBIAN_FRONTEND=noninteractive apt-get install -y apt-cacher-ng && \
	rm -rf /var/lib/apt/lists/*

CMD     /etc/init.d/apt-cacher-ng start && tail -f /var/log/apt-cacher-ng/*

EOF

podman container create --name=apt-cacher-ng \
  --net=host --dns=127.0.0.53 --dns-opt='edns0 trust-ad' \
  --volume apt-cacher-ng:/var/cache/apt-cacher-ng \
  apt-cacher-ng

podman generate systemd --new --name apt-cacher-ng > ~/.config/systemd/user/container-apt-cacher-ng.service
podman container rm -f apt-cacher-ng

systemctl --user daemon-reload
systemctl --user enable --now container-apt-cacher-ng.service
