#!/bin/sh -eux

LOCALES="en_US en_CA en_DK de_DE en_IE"
RELEASE=${1:-$(. /lib/os-release && echo $VERSION_ID)}

toolbox rm -f f$RELEASE || true
toolbox -y create -c f$RELEASE -r ${RELEASE}

podman start f$RELEASE
run() { podman exec -i f$RELEASE "$@"; }

source ./toolbox-packages

run dnf update -y
run dnf build-dep -y ${build_deps}
run dnf install -y ${packages} ${fedora_packages}

run ln -Tsf host/run/pcscd /run/pcscd
