#!/bin/sh -eux

LOCALES="en_US en_CA en_DK de_DE en_IE"
RELEASE=${1:-$(. /lib/os-release && echo $VERSION_ID)}
NAME="fedora-toolbox-${RELEASE}"

toolbox rm -f ${NAME} || true
toolbox -y create -r ${RELEASE}

podman start ${NAME}
run() { podman exec -i "${NAME}" "$@"; }

source ./toolbox-packages

run dnf update -y
run dnf build-dep -y ${build_deps}
run dnf install -y ${packages} ${fedora_packages}

run ln -Tsf host/run/pcscd /run/pcscd
